set_property -dict {PACKAGE_PIN V4      IOSTANDARD LVCMOS33 } [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_ports clk]

set_property -dict {PACKAGE_PIN M13     IOSTANDARD LVCMOS33 } [get_ports reset]

set_property -dict {PACKAGE_PIN N13     IOSTANDARD LVCMOS33 } [get_ports pause]

set_property -dict {PACKAGE_PIN W9      IOSTANDARD LVCMOS33 } [get_ports sec[0]]
set_property -dict {PACKAGE_PIN AB7     IOSTANDARD LVCMOS33 } [get_ports sec[1]]
set_property -dict {PACKAGE_PIN AA6     IOSTANDARD LVCMOS33 } [get_ports sec[2]]
set_property -dict {PACKAGE_PIN W5      IOSTANDARD LVCMOS33 } [get_ports sec[3]]

set_property -dict {PACKAGE_PIN W4      IOSTANDARD LVCMOS33 } [get_ports sec10[0]]
set_property -dict {PACKAGE_PIN Y1      IOSTANDARD LVCMOS33 } [get_ports sec10[1]]
set_property -dict {PACKAGE_PIN V3      IOSTANDARD LVCMOS33 } [get_ports sec10[2]]
set_property -dict {PACKAGE_PIN U2      IOSTANDARD LVCMOS33 } [get_ports sec10[3]]

set_property -dict {PACKAGE_PIN AB8     IOSTANDARD LVCMOS33 } [get_ports min[0]]
set_property -dict {PACKAGE_PIN Y7      IOSTANDARD LVCMOS33 } [get_ports min[1]]
set_property -dict {PACKAGE_PIN Y6      IOSTANDARD LVCMOS33 } [get_ports min[2]]
set_property -dict {PACKAGE_PIN AA4     IOSTANDARD LVCMOS33 } [get_ports min[3]]

set_property -dict {PACKAGE_PIN AA3     IOSTANDARD LVCMOS33 } [get_ports min10[0]]
set_property -dict {PACKAGE_PIN Y2      IOSTANDARD LVCMOS33 } [get_ports min10[1]]
set_property -dict {PACKAGE_PIN U1      IOSTANDARD LVCMOS33 } [get_ports min10[2]]
set_property -dict {PACKAGE_PIN R3      IOSTANDARD LVCMOS33 } [get_ports min10[3]]

set_property -dict {PACKAGE_PIN T1      IOSTANDARD LVCMOS33 } [get_ports hour[0]]
set_property -dict {PACKAGE_PIN T3      IOSTANDARD LVCMOS33 } [get_ports hour[1]]
set_property -dict {PACKAGE_PIN U3      IOSTANDARD LVCMOS33 } [get_ports hour[2]]
set_property -dict {PACKAGE_PIN V2      IOSTANDARD LVCMOS33 } [get_ports hour[3]]
set_property -dict {PACKAGE_PIN W1      IOSTANDARD LVCMOS33 } [get_ports hour[4]]
set_property -dict {PACKAGE_PIN W2      IOSTANDARD LVCMOS33 } [get_ports hour[5]]
set_property -dict {PACKAGE_PIN Y3      IOSTANDARD LVCMOS33 } [get_ports hour[6]]
set_property -dict {PACKAGE_PIN AA1     IOSTANDARD LVCMOS33 } [get_ports hour[7]]

set_property -dict {PACKAGE_PIN AB2     IOSTANDARD LVCMOS33 } [get_ports hour10[0]]
set_property -dict {PACKAGE_PIN AB1     IOSTANDARD LVCMOS33 } [get_ports hour10[1]]
set_property -dict {PACKAGE_PIN Y4      IOSTANDARD LVCMOS33 } [get_ports hour10[2]]
set_property -dict {PACKAGE_PIN AB3     IOSTANDARD LVCMOS33 } [get_ports hour10[3]]
set_property -dict {PACKAGE_PIN AB5     IOSTANDARD LVCMOS33 } [get_ports hour10[4]]
set_property -dict {PACKAGE_PIN AA5     IOSTANDARD LVCMOS33 } [get_ports hour10[5]]
set_property -dict {PACKAGE_PIN W7      IOSTANDARD LVCMOS33 } [get_ports hour10[6]]
set_property -dict {PACKAGE_PIN AB6     IOSTANDARD LVCMOS33 } [get_ports hour10[7]]

set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS33 } [get_ports AP[0]]
set_property -dict {PACKAGE_PIN Y8  IOSTANDARD LVCMOS33 } [get_ports AP[1]]
set_property -dict {PACKAGE_PIN R4  IOSTANDARD LVCMOS33 } [get_ports AP[2]]
set_property -dict {PACKAGE_PIN Y9  IOSTANDARD LVCMOS33 } [get_ports AP[3]]
set_property -dict {PACKAGE_PIN U5  IOSTANDARD LVCMOS33 } [get_ports AP[4]]
set_property -dict {PACKAGE_PIN T5  IOSTANDARD LVCMOS33 } [get_ports AP[5]]
set_property -dict {PACKAGE_PIN V7  IOSTANDARD LVCMOS33 } [get_ports AP[6]]
set_property -dict {PACKAGE_PIN U6  IOSTANDARD LVCMOS33 } [get_ports AP[7]]

set_property -dict {PACKAGE_PIN V9  IOSTANDARD LVCMOS33 } [get_ports day[0]]
set_property -dict {PACKAGE_PIN V8  IOSTANDARD LVCMOS33 } [get_ports day[1]]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33 } [get_ports day[2]]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33 } [get_ports day[3]]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33 } [get_ports day[4]]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33 } [get_ports day[5]]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33 } [get_ports day[6]]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33 } [get_ports day[7]]