@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Dec 16 21:30:16 +0800 2024
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 01df3b66dca24ad4b67c26cdd3d533ff --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_O_CLOCK_behav xil_defaultlib.tb_O_CLOCK -log elaborate.log"
call xelab  -wto 01df3b66dca24ad4b67c26cdd3d533ff --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_O_CLOCK_behav xil_defaultlib.tb_O_CLOCK -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
